version: "3"

services:
  postgres:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=3.x
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=base64:7j3B2qtaZ0olHj6rIk2CBaBEeYtGSxLo2e+HbrfItKU=
      - APP_LOG=errorlog
      - APP_ENV:development
      - APP_DEBUG=true
      - DEBUG=true
    depends_on:
      - postgres
    restart: on-failure
